id: IF3F575F2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T18:23:05+00:00'
last_modified: '2022-06-07T10:42:45.180707+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4884
  title: གསུང་འབུམ། དྲི་མེད་འོད་ཟེར། （དཔལ་བརྩེགས། མེས་པོའི་ཤུལ་བཞག）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1C5D:
      image_group_id: I1KG4886
      title: Volume 1 of gsung 'bum/_dri med 'od zer
      total_pages: 392
      order: 1
      base_file: 1C5D.txt
    '8191':
      image_group_id: I1KG4887
      title: Volume 2 of gsung 'bum/_dri med 'od zer
      total_pages: 414
      order: 2
      base_file: 8191.txt
    '4627':
      image_group_id: I1KG4888
      title: Volume 3 of gsung 'bum/_dri med 'od zer
      total_pages: 394
      order: 3
      base_file: 4627.txt
    BD5A:
      image_group_id: I1KG4889
      title: Volume 4 of gsung 'bum/_dri med 'od zer
      total_pages: 338
      order: 4
      base_file: BD5A.txt
    EFCF:
      image_group_id: I1KG4890
      title: Volume 5 of gsung 'bum/_dri med 'od zer
      total_pages: 514
      order: 5
      base_file: EFCF.txt
    2CAA:
      image_group_id: I1KG4891
      title: Volume 6 of gsung 'bum/_dri med 'od zer
      total_pages: 516
      order: 6
      base_file: 2CAA.txt
    440A:
      image_group_id: I1KG4892
      title: Volume 7 of gsung 'bum/_dri med 'od zer
      total_pages: 550
      order: 7
      base_file: 440A.txt
    C8C0:
      image_group_id: I1KG4893
      title: Volume 8 of gsung 'bum/_dri med 'od zer
      total_pages: 430
      order: 8
      base_file: C8C0.txt
    D5FA:
      image_group_id: I1KG4894
      title: Volume 9 of gsung 'bum/_dri med 'od zer
      total_pages: 358
      order: 9
      base_file: D5FA.txt
    99E9:
      image_group_id: I1KG4895
      title: Volume 10 of gsung 'bum/_dri med 'od zer
      total_pages: 366
      order: 10
      base_file: 99E9.txt
    F4DF:
      image_group_id: I1KG4896
      title: Volume 11 of gsung 'bum/_dri med 'od zer
      total_pages: 374
      order: 11
      base_file: F4DF.txt
    6DCB:
      image_group_id: I1KG4897
      title: Volume 12 of gsung 'bum/_dri med 'od zer
      total_pages: 394
      order: 12
      base_file: 6DCB.txt
    13B1:
      image_group_id: I1KG4898
      title: Volume 13 of gsung 'bum/_dri med 'od zer
      total_pages: 516
      order: 13
      base_file: 13B1.txt
    FE2C:
      image_group_id: I1KG4899
      title: Volume 14 of gsung 'bum/_dri med 'od zer
      total_pages: 556
      order: 14
      base_file: FE2C.txt
    BEBC:
      image_group_id: I1KG4900
      title: Volume 15 of gsung 'bum/_dri med 'od zer
      total_pages: 510
      order: 15
      base_file: BEBC.txt
    544E:
      image_group_id: I1KG4901
      title: Volume 16 of gsung 'bum/_dri med 'od zer
      total_pages: 434
      order: 16
      base_file: 544E.txt
    C025:
      image_group_id: I1KG4902
      title: Volume 17 of gsung 'bum/_dri med 'od zer
      total_pages: 634
      order: 17
      base_file: C025.txt
    A438:
      image_group_id: I1KG4903
      title: Volume 18 of gsung 'bum/_dri med 'od zer
      total_pages: 546
      order: 18
      base_file: A438.txt
    6C0E:
      image_group_id: I1KG4904
      title: Volume 19 of gsung 'bum/_dri med 'od zer
      total_pages: 446
      order: 19
      base_file: 6C0E.txt
    AD19:
      image_group_id: I1KG4905
      title: Volume 20 of gsung 'bum/_dri med 'od zer
      total_pages: 498
      order: 20
      base_file: AD19.txt
    A48E:
      image_group_id: I1KG4906
      title: Volume 21 of gsung 'bum/_dri med 'od zer
      total_pages: 598
      order: 21
      base_file: A48E.txt
    BA65:
      image_group_id: I1KG4907
      title: Volume 22 of gsung 'bum/_dri med 'od zer
      total_pages: 542
      order: 22
      base_file: BA65.txt
    '8068':
      image_group_id: I1KG4908
      title: Volume 23 of gsung 'bum/_dri med 'od zer
      total_pages: 598
      order: 23
      base_file: 8068.txt
    D2B3:
      image_group_id: I1KG4909
      title: Volume 24 of gsung 'bum/_dri med 'od zer
      total_pages: 454
      order: 24
      base_file: D2B3.txt
    9E33:
      image_group_id: I1KG4910
      title: Volume 25 of gsung 'bum/_dri med 'od zer
      total_pages: 514
      order: 25
      base_file: 9E33.txt
    5BBA:
      image_group_id: I1KG4911
      title: Volume 26 of gsung 'bum/_dri med 'od zer
      total_pages: 342
      order: 26
      base_file: 5BBA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
